apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance-service
  template:
    metadata:
      labels:
        app: insurance-service
    spec:
      containers:
        - name: insurance-service
          image: rental/insurance-service:latest
          ports:
            - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: insurance-service
spec:
  selector:
    app: insurance-service
  ports:
    - port: 8085
      targetPort: 8085
  type: ClusterIP